In [ ]:
Consider the below code to answer further questions:
import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)

In [ ]:
Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

Yes, there is a difference in the data type of variables `list_` and `array_list`. 

The variable `list_` is a Python list, whereas `array_list` is a NumPy array.

You can verify the data types of both variables using the `type()` function. Here's the code:

import numpy as np

# Define the list
list_ = ['1', '2', '3', '4', '5']

# Convert the list to a NumPy array
array_list = np.array(object=list_)

# Print the data types of both variables
print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))
```

This code will output:

Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>

As you can see, `list_` is of type `list`, while `array_list` is of type `numpy.ndarray`.

In [ ]:
Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

To print the data type of each element in both the `list_` and `array_list`, you can iterate through the elements and use the `type()` function to determine the data type of each element. Here's the code:

import numpy as np

# Define the list
list_ = ['1', '2', '3', '4', '5']

# Convert the list to a NumPy array
array_list = np.array(object=list_)

# Print the data type of each element in the list
print("Data type of each element in list_:")
for elem in list_:
    print(type(elem))

# Print the data type of each element in the NumPy array
print("\nData type of each element in array_list:")
for elem in array_list:
    print(type(elem))

This code will output the data type of each element in both the `list_` and `array_list`. However, please note that since all elements in `list_` are strings, the data types of each element in `list_` will be `<class 'str'>`. In the `array_list`, the data type of each element will depend on how NumPy interprets the data during array creation. If the elements can be interpreted as numbers, NumPy may convert them to numeric data types. Otherwise, they will remain as strings.

In [ ]:
Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

Yes, there will be a difference in the data type of the elements present in both the variables `list_` and `array_list` after the specified change. When you create the NumPy array `array_list` using `dtype=int`, the elements will be explicitly converted to integer data type.

Here's the code to print the data types of each element present in both `list_` and `array_list` after the change:

import numpy as np

# Define the list
list_ = ['1', '2', '3', '4', '5']

# Convert the list to a NumPy array with dtype=int
array_list = np.array(object=list_, dtype=int)

# Print the data type of each element in the list
print("Data type of each element in list_:")
for elem in list_:
    print(type(elem))

# Print the data type of each element in the NumPy array
print("\nData type of each element in array_list:")
for elem in array_list:
    print(type(elem))

After executing this code, you will see that the data type of each element in `list_` remains as `<class 'str'>`, while the data type of each element in `array_list` will be `<class 'int'>`. This is because the `dtype=int` argument explicitly specifies that the elements should be converted to integers when creating the NumPy array.

In [ ]:
Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [ ]:
Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

You can find the shape and size of the NumPy array `num_array` using the `shape` and `size` attributes respectively. Here's the code:

import numpy as np

# Define the list
num_list = [[1, 2, 3], [4, 5, 6]]

# Convert the list to a NumPy array
num_array = np.array(object=num_list)

# Find the shape of the array
array_shape = num_array.shape

# Find the size of the array
array_size = num_array.size

# Print the characteristics of the array
print("Shape of the array:", array_shape)
print("Size of the array:", array_size)

This code will output:

Shape of the array: (2, 3)
Size of the array: 6

In [ ]:
Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

You can create a NumPy array of a 3x3 matrix containing zeros only using the `np.zeros()` function. Here's the code:

import numpy as np

# Create a NumPy array of zeros with shape (3, 3)
zero_array = np.zeros((3, 3))

print("Array of zeros:")
print(zero_array)

This code will output:

Array of zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

In [ ]:
Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

You can create an identity matrix of shape (5, 5) using the `np.eye()` function from NumPy. Here's the code:

import numpy as np

# Create an identity matrix of shape (5, 5)
identity_matrix = np.eye(5)

print("Identity Matrix:")
print(identity_matrix)

This code will output:

Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]